CREATE TABLE usermanagement.USER
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);