CREATE TABLE usermanagement.ROLE
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_role     VARCHAR(255),
    user_id       BIGINT,

    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,

    CONSTRAINT fk_user_role_on_user FOREIGN KEY (user_id)
        REFERENCES usermanagement.USER (id)
);

ALTER TABLE usermanagement.ROLE
    ADD CONSTRAINT CHECK_ROLE_ON_USER_ROLE CHECK (user_role IN ('ADMIN', 'USER'));